version: '3.8'

services:
  app:
    build: .
    ports:
      - "5066:5066"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://admin:admin@db:5432/url_shortener

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: url_shortener
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d url_shortener"]
      interval: 10s
      timeout: 5s
      retries: 5