"""DB init

Revision ID: 0c1e3ba1849b
Revises: 
Create Date: 2024-08-02 17:40:58.185805

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c1e3ba1849b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_mapping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('short_url', sa.String(length=7), nullable=False),
    sa.Column('long_url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_url')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('url_mapping')
    # ### end Alembic commands ###
